export const activeEvents = [
  {
    eventId: "evt-active-001",
    type: "speed.violation_alert",
    priority: "critical",
    location: "North Belt / Sector 4",
    deviceName: "Patrol Radar 07",
    trackLabel: "car",
    speed: 121,
    speedLimit: 90,
    confidence: 0.94,
    status: "escalated",
    updatedAt: "2026-04-22T10:28:00Z",
  },
  {
    eventId: "evt-active-002",
    type: "fused.vehicle_event",
    priority: "warning",
    location: "City Entry / Lane 2",
    deviceName: "Road Cam 03",
    trackLabel: "truck",
    speed: 87,
    speedLimit: 70,
    confidence: 0.81,
    status: "review",
    updatedAt: "2026-04-22T10:24:00Z",
  },
  {
    eventId: "evt-active-003",
    type: "speed.violation_alert",
    priority: "critical",
    location: "Industrial Corridor",
    deviceName: "Bridge Radar 02",
    trackLabel: "motorcycle",
    speed: 109,
    speedLimit: 70,
    confidence: 0.89,
    status: "dispatching",
    updatedAt: "2026-04-22T10:22:00Z",
  },
];

export const eventHistory = [
  {
    eventId: "evt-history-101",
    type: "speed.violation_alert",
    outcome: "ticket-issued",
    deviceName: "Patrol Radar 07",
    location: "North Belt / Sector 4",
    speed: 118,
    speedLimit: 90,
    confidence: 0.91,
    occurredAt: "2026-04-22T09:58:00Z",
  },
  {
    eventId: "evt-history-102",
    type: "fused.vehicle_event",
    outcome: "dismissed",
    deviceName: "Road Cam 03",
    location: "City Entry / Lane 2",
    speed: 73,
    speedLimit: 70,
    confidence: 0.52,
    occurredAt: "2026-04-22T09:44:00Z",
  },
  {
    eventId: "evt-history-103",
    type: "detection.event",
    outcome: "archived",
    deviceName: "Tunnel Cam 11",
    location: "Tunnel West",
    speed: 0,
    speedLimit: 70,
    confidence: 0.77,
    occurredAt: "2026-04-22T09:33:00Z",
  },
  {
    eventId: "evt-history-104",
    type: "speed.violation_alert",
    outcome: "under-review",
    deviceName: "Bridge Radar 02",
    location: "Industrial Corridor",
    speed: 96,
    speedLimit: 70,
    confidence: 0.87,
    occurredAt: "2026-04-22T09:16:00Z",
  },
  {
    eventId: "evt-history-105",
    type: "fused.vehicle_event",
    outcome: "validated",
    deviceName: "Road Cam 09",
    location: "Harbor Route",
    speed: 89,
    speedLimit: 80,
    confidence: 0.84,
    occurredAt: "2026-04-22T08:54:00Z",
  },
];

export const devices = [
  {
    deviceId: "radar-07",
    name: "Patrol Radar 07",
    type: "mobile-radar",
    zone: "North Belt",
    status: "online",
    health: 98,
    streamState: "stable",
    lastSeen: "2026-04-22T10:29:00Z",
    metrics: {
      fps: 24,
      latencyMs: 120,
      battery: 81,
    },
  },
  {
    deviceId: "cam-03",
    name: "Road Cam 03",
    type: "fixed-camera",
    zone: "City Entry",
    status: "online",
    health: 94,
    streamState: "stable",
    lastSeen: "2026-04-22T10:29:00Z",
    metrics: {
      fps: 20,
      latencyMs: 145,
      battery: null,
    },
  },
  {
    deviceId: "cam-11",
    name: "Tunnel Cam 11",
    type: "fixed-camera",
    zone: "Tunnel West",
    status: "maintenance",
    health: 72,
    streamState: "degraded",
    lastSeen: "2026-04-22T10:11:00Z",
    metrics: {
      fps: 12,
      latencyMs: 380,
      battery: null,
    },
  },
  {
    deviceId: "radar-02",
    name: "Bridge Radar 02",
    type: "bridge-radar",
    zone: "Industrial Corridor",
    status: "offline",
    health: 33,
    streamState: "unavailable",
    lastSeen: "2026-04-22T09:52:00Z",
    metrics: {
      fps: 0,
      latencyMs: null,
      battery: 19,
    },
  },
];

export const liveStreams = [
  {
    streamId: "stream-01",
    title: "North Belt Lane Overview",
    source: "rtsp://north-belt-cam-01",
    state: "placeholder",
    latencyMs: 124,
    deviceName: "Patrol Radar 07",
  },
  {
    streamId: "stream-02",
    title: "City Entry Merge Point",
    source: "rtsp://city-entry-cam-03",
    state: "placeholder",
    latencyMs: 148,
    deviceName: "Road Cam 03",
  },
];
